name: Build micro (Mac OS x86)

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build micro.sfx
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      # Install macOS missing packages and mark os suffix
      - run: brew install automake autoconf libiconv

      # Download last SPC version
      - run: curl -fsSL -o spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-macos-x86_64 && chmod +x spc

      # Run build command
      - run: ./spc download --with-php=8.2 --for-extensions "bcmath,ctype,dom,fileinfo,filter,ftp,libxml,mbregex,mbstring,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,session,simplexml,sockets,sqlite3,ssh2,tokenizer,xml,yaml,zip,zlib,curl"

      # Compile
      - run: ./spc build --build-micro "bcmath,ctype,dom,fileinfo,filter,ftp,libxml,mbregex,mbstring,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,session,simplexml,sockets,sqlite3,ssh2,tokenizer,xml,yaml,zip,zlib,curl"

      # Upload micro.sfx executable
      - uses: actions/upload-artifact@v4
        with:
          name: micro-macos-x86.sfx
          path: buildroot/bin/micro.sfx
