name: Create release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        ini-values: phar.readonly=Off

    - uses: actions/checkout@v4

    - name: Setting vars
      id: vars
      run: echo ::set-output name=distname::$(echo ${{ github.event.repository.name }}-$(git tag | tail -1).zip)

    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies (Dev)
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test

    - name: Install dependencies (Production)
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Creating application
      run: php application app:build mybackup.phar --build-version=${{ steps.previoustag.outputs.tag }} -n -q

    - name: Ensure the PHAR works
      run: php builds/mybackup.phar --version

    - name: Upload release PHAR version
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/mybackup.phar
        asset_name: mybackup.phar
        overwrite: true

    - name: Downloading micro.sfx from Build micro (Linux aarch64)
      uses: actions/download-artifact@v4
      with:
        path: builds
        run-id: 12930692838
        github-token: ${{ github.token }}

    - name: Downloading micro.sfx from Build micro (Linux amd64)
      uses: actions/download-artifact@v4
      with:
        path: builds
        run-id: 12930694381
        github-token: ${{ github.token }}

    - name: Downloading micro.sfx from Build micro (MacOs aarch64)
      uses: actions/download-artifact@v4
      with:
        path: builds
        run-id: 12930696130
        github-token: ${{ github.token }}

    - name: Downloading micro.sfx from Build micro (MacOs x86)
      uses: actions/download-artifact@v4
      with:
        path: builds
        run-id: 12930697451
        github-token: ${{ github.token }}

    - name: Listing build directory
      run: ls -R builds

    - name: Build Linux executable (aarch64)
      run: mv builds/micro-linux-aarch64.sfx/micro.sfx builds/mybackup-linux-aarch64-${{ steps.previoustag.outputs.tag }} && cat builds/mybackup.phar >> builds/mybackup-linux-aarch64-${{ steps.previoustag.outputs.tag }}

    - name: Upload Linux executable (aarch64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/mybackup-linux-aarch64-${{ steps.previoustag.outputs.tag }}
        asset_name: mybackup-linux-aarch64-${{ steps.previoustag.outputs.tag }}
        overwrite: true

    - name: Build Linux executable (x86)
      run: mv builds/micro-linux-x86.sfx/micro.sfx builds/mybackup-linux-amd64-${{ steps.previoustag.outputs.tag }} && cat builds/mybackup.phar >> builds/mybackup-linux-amd64-${{ steps.previoustag.outputs.tag }}

    - name: Upload Linux executable (x86)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/mybackup-linux-amd64-${{ steps.previoustag.outputs.tag }}
        asset_name: mybackup-linux-amd64-${{ steps.previoustag.outputs.tag }}
        overwrite: true

    - name: Build MacOs executable (aarch64)
      run: mv builds/micro-macos-aarch64.sfx/micro.sfx builds/mybackup-macos-aarch64-${{ steps.previoustag.outputs.tag }} && cat builds/mybackup.phar >> builds/mybackup-macos-aarch64-${{ steps.previoustag.outputs.tag }}

    - name: Upload MacOs executable (aarch64)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/mybackup-macos-aarch64-${{ steps.previoustag.outputs.tag }}
        asset_name: mybackup-macos-aarch64-${{ steps.previoustag.outputs.tag }}
        overwrite: true

    - name: Build MacOs executable (x86)
      run: mv builds/micro-macos-x86.sfx/micro.sfx builds/mybackup-macos-x86-${{ steps.previoustag.outputs.tag }} && cat builds/mybackup.phar >> builds/mybackup-macos-x86-${{ steps.previoustag.outputs.tag }}

    - name: Upload MacOs executable (x86)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/mybackup-macos-x86-${{ steps.previoustag.outputs.tag }}
        asset_name: mybackup-macos-x86-${{ steps.previoustag.outputs.tag }}
        overwrite: true
